apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    editable: true
    jsonData:
      timeInterval: 15s

  - name: VictoriaMetrics-Prom-Sink
    type: prometheus
    access: proxy
    url: http://victoriametrics-prom-sink:8428
    editable: true
    jsonData:
      timeInterval: 15s
